Repository opensearch-project/opensearch-build-libraries, pull requests merged in 2023-10, with the labels that each got.

#318 Refactoring var scopes in uploadMinSnapshotsToS3 libs
  build.gradle
  tests/data/opensearch-1.3.0-build.yml
  tests/data/tar/builds/opensearch/manifest.yml
  tests/jenkins/TestCreateUploadTestReportManifest.groovy
  tests/jenkins/TestRunIntegTestScript.groovy
  tests/jenkins/TestUploadMinSnapshotsToS3.groovy
  tests/jenkins/jobs/CreateUploadTestReportManifest_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_LocalPath_Switch_Non_Root_Jenkinsfile.txt
  tests/jenkins/jobs/UploadTestResults_Jenkinsfile.txt
  tests/jenkins/jobs/uploadMinSnapshotsToS3_Jenkinsfile
  tests/jenkins/jobs/uploadMinSnapshotsToS3_Jenkinsfile.txt
  tests/jenkins/lib-testers/UploadMinSnapshotsToS3LibTester.groovy
  vars/uploadMinSnapshotsToS3.groovy
Labels: bug, enhancement, backport 5.x

#323 [Backport 5.x] Refactoring var scopes in uploadMinSnapshotsToS3 libs
  build.gradle
  tests/data/opensearch-1.3.0-build.yml
  tests/data/tar/builds/opensearch/manifest.yml
  tests/jenkins/TestCreateUploadTestReportManifest.groovy
  tests/jenkins/TestRunIntegTestScript.groovy
  tests/jenkins/TestUploadMinSnapshotsToS3.groovy
  tests/jenkins/jobs/CreateUploadTestReportManifest_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_LocalPath_Switch_Non_Root_Jenkinsfile.txt
  tests/jenkins/jobs/UploadTestResults_Jenkinsfile.txt
  tests/jenkins/jobs/uploadMinSnapshotsToS3_Jenkinsfile
  tests/jenkins/jobs/uploadMinSnapshotsToS3_Jenkinsfile.txt
  tests/jenkins/lib-testers/UploadMinSnapshotsToS3LibTester.groovy
  vars/uploadMinSnapshotsToS3.groovy
Labels: backport

#330 Make sure windows correctly switch java versions in integTest
  build.gradle
  vars/runIntegTestScript.groovy
Labels: bug, windows, backport 5.x

#347 Update `createGithubIssue` to re-open recently closed issue
  .gitignore
  build.gradle
  tests/jenkins/TestCreateBuildFailureGithubIssue.groovy
  tests/jenkins/TestCreateGithubIssue.groovy
  tests/jenkins/jobs/CreateBuildFailureGithubExistingIssueCheck_Jenkinsfile.txt
  tests/jenkins/jobs/CreateBuildFailureGithubIssue_Jenkinsfile.txt
  tests/jenkins/jobs/CreateGithubIssueExisting_JenkinsFile
  tests/jenkins/jobs/CreateGithubIssueExisting_JenkinsFile.txt
  tests/jenkins/jobs/CreateGithubIssue_Jenkinsfile
  tests/jenkins/jobs/CreateGithubIssue_Jenkinsfile.txt
  tests/jenkins/lib-testers/CreateGithubIssueLibTester.groovy
  vars/createGithubIssue.groovy
Labels: enhancement, backport 5.x
