Repository opensearch-project/opensearch-build-libraries, pull requests merged in 2023-07, with the labels that each got.

#249 Add docker login for both source and dest registries
  build.gradle
  tests/jenkins/TestCopyContainer.groovy
  tests/jenkins/jobs/DockerCopyAllTags_Jenkinsfile.txt
  tests/jenkins/jobs/DockerCopy_Jenkinsfile.txt
  vars/copyContainer.groovy
Labels: bug, enhancement, backport 5.x

#254 Make docker command detection consistently across OSes
  build.gradle
  tests/jenkins/jobs/RunGradleCheck_Jenkinsfile.txt
  vars/runGradleCheck.groovy
Labels: bug, backport 5.x

#260 Fix trigger branch for version increment
  .github/workflows/version-increment.yml
Labels: backport 5.x

#261 Fix the README
  README.md
Labels: backport 5.x

#265 Fix the hardcoded query string bug for closeBuildSuccessGithubIssue
  build.gradle
  tests/jenkins/TestCloseBuildSuccessGithubIssue.groovy
  tests/jenkins/jobs/CloseBuildSuccessGithubIssue_JenkinsFile
  tests/jenkins/jobs/CloseBuildSuccessGithubIssue_JenkinsFile.txt
  tests/jenkins/lib-testers/CloseBuildSuccessGithubIssueLibTester.groovy
  vars/closeBuildSuccessGithubIssue.groovy
Labels: backport 5.x
