Repository opensearch-project/opensearch-build-libraries, pull requests merged in 2024-10, with the labels that each got.

#510 Revert to the `gradle-check` alias logic rather than querying `-*` gradle check indices
  build.gradle
  src/gradlecheck/OpenSearchMetricsQuery.groovy
  vars/publishGradleCheckTestResults.groovy
Labels: backport 6.x

#536 Publish the failing test's name and class along with the integration test results
  build.gradle
  tests/jenkins/TestPublishIntegTestResults.groovy
  vars/publishIntegTestResults.groovy
Labels: backport 7.x

#540 For publish libraries update the index alias mapping logic
  tests/jenkins/TestPublishDistributionBuildResults.groovy
  vars/publishDistributionBuildResults.groovy
  vars/publishGradleCheckTestResults.groovy
Labels: backport 7.x

#542 Use HOME var instead of tilde to be more comparible with Windows
  build.gradle
  tests/jenkins/TestRetrievePreviousBuild.groovy
  tests/jenkins/jobs/BuildShManifestIncremental_Jenkinsfile.txt
  tests/jenkins/jobs/RetrievePreviousBuild_Jenkinsfile.txt
  vars/retrievePreviousBuild.groovy
Labels: enhancement, windows, backport 7.x, v2.18.0

#551 Create GH label if one is missing while creating GH issues
  tests/jenkins/TestCreateGithubIssue.groovy
  vars/createGithubIssue.groovy
Labels: backport 7.x
