Repository opensearch-project/opensearch-build-libraries, pull requests merged in 2025-04, with the labels that each got.

#648 Fix release issue query to exactly match the repo name
  src/jenkins/ReleaseMetricsData.groovy
  tests/jenkins/TestReleaseMetricsData.groovy
Labels: backport 8.x

#650 Fix default value in the release issue method
  build.gradle
  src/jenkins/ReleaseMetricsData.groovy
  tests/jenkins/TestAddRcDetailsComment.groovy
  tests/jenkins/TestCheckCodeCoverage.groovy
  tests/jenkins/TestCheckRequestAssignReleaseOwners.groovy
  tests/jenkins/jobs/AddRcDetailsComment.jenkinsFile.txt
  tests/jenkins/jobs/CheckCodeCoverage_Jenkinsfile.txt
Labels: backport 8.x

#641 Update the signing libraries with additional email parameters (9.x)
  .github/workflows/version-increment.yml
  build.gradle
  tests/jenkins/TestPromoteRepos.groovy
  tests/jenkins/TestPublishToMaven.groovy
  tests/jenkins/jobs/AssembleManifest_rpm_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifactsQualifier_actions_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifactsQualifier_actions_Jenkinsfile_Windows.txt.txt
  tests/jenkins/jobs/PromoteArtifactsQualifier_actions_OpenSearch_Dashboards_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifactsQualifier_actions_OpenSearch_Dashboards_Jenkinsfile_Windows.txt.txt
  tests/jenkins/jobs/PromoteArtifacts_actions_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifacts_actions_Jenkinsfile_Windows.txt.txt
  tests/jenkins/jobs/PromoteArtifacts_actions_OpenSearch_Dashboards_Jenkinsfile.txt
  tests/jenkins/jobs/PromoteArtifacts_actions_OpenSearch_Dashboards_Jenkinsfile_Windows.txt.txt
  tests/jenkins/jobs/PromoteRepos_Jenkinsfile.txt
  tests/jenkins/jobs/PublishToArtifactsProdBucket_Jenkinsfile.txt
  tests/jenkins/jobs/PublishToMavenManifestYml_Jenkinsfile.txt
  tests/jenkins/jobs/PublishToMaven_Jenkinsfile.txt
  tests/jenkins/jobs/PublishToPyPiWithDir_Jenkinsfile.txt
  tests/jenkins/jobs/PublishToPyPi_Jenkinsfile.txt
  tests/jenkins/jobs/SignArtifacts_Jenkinsfile.txt
  vars/promoteArtifacts.groovy
  vars/promoteRepos.groovy
  vars/publishToMaven.groovy
  vars/signArtifacts.groovy
  vars/uploadMinSnapshotsToS3.groovy
Labels: backport 9.x

#658 Ensure rpm sign has correct email switch based on version
  tests/data/opensearch-build-3.0.0-alpha1-rpm.yml
  tests/jenkins/jobs/AssembleManifest_rpm_Jenkinsfile
  tests/jenkins/jobs/AssembleManifest_rpm_Jenkinsfile.txt
  tests/jenkins/jobs/SignArtifacts_Jenkinsfile
  tests/jenkins/jobs/SignArtifacts_Jenkinsfile.txt
  vars/assembleManifest.groovy
  vars/signArtifacts.groovy
Labels: enhancement, backport 9.x

#662 [Backport 9.x] Ensure rpm sign has correct email switch based on version
  tests/data/opensearch-build-3.0.0-alpha1-rpm.yml
  tests/jenkins/jobs/AssembleManifest_rpm_Jenkinsfile
  tests/jenkins/jobs/AssembleManifest_rpm_Jenkinsfile.txt
  tests/jenkins/jobs/SignArtifacts_Jenkinsfile
  tests/jenkins/jobs/SignArtifacts_Jenkinsfile.txt
  vars/assembleManifest.groovy
  vars/signArtifacts.groovy
Labels: enhancement

#674 Use dynamic type instead of strong type
  src/jenkins/ComponentBuildStatus.groovy
  src/jenkins/ComponentIntegTestStatus.groovy
Labels: backport 9.x
