Repository opensearch-project/opensearch-build-libraries, pull requests merged in 2025-03, with the labels that each got.

#593 Update trivy image scan cleanup commands
  build.gradle
  tests/jenkins/jobs/ScanDockerImage_Jenkinsfile.txt
  vars/scanDockerImage.groovy
Labels: enhancement, backport 8.x

#606 Update OpenSearch gradle check version file location
  tests/jenkins/jobs/RunGradleCheckBwcAlign_Jenkinsfile.txt
  tests/jenkins/jobs/RunGradleCheck_Jenkinsfile.txt
  vars/runGradleCheck.groovy
Labels: enhancement, backport 8.x, backport 8.2

#611 Add qualifier support to metrics queries
  src/jenkins/ComponentBuildStatus.groovy
  src/jenkins/ComponentIntegTestStatus.groovy
  src/jenkins/ReleaseCandidateStatus.groovy
  tests/jenkins/TestComponentBuildStatus.groovy
  tests/jenkins/TestComponentIntegTestStatus.groovy
  tests/jenkins/TestPublishDistributionBuildResults.groovy
  tests/jenkins/TestPublishIntegTestResults.groovy
  tests/jenkins/TestReleaseCandidateStatus.groovy
  tests/jenkins/jobs/CheckRequestAssignReleaseOwnerJenkinsFile.txt
  vars/addRcDetailsComment.groovy
  vars/checkRequestAssignReleaseOwners.groovy
  vars/publishDistributionBuildResults.groovy
  vars/publishIntegTestResults.groovy
  vars/updateBuildFailureIssues.groovy
  vars/updateIntegTestFailureIssues.groovy
Labels: backport 8.x

#614 Update integTest manifests path to remove leading 'manifests' prefix
  build.gradle
  tests/jenkins/TestRunIntegTestScript.groovy
  tests/jenkins/TestRunIntegTestScriptForOSD.groovy
  tests/jenkins/jobs/RunIntegTestScriptForOSDCiGroup_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScriptForOSD_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_LocalPath_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_LocalPath_Switch_Non_Root_Jenkinsfile.txt
  vars/runIntegTestScript.groovy
Labels: enhancement, backport 8.x

#617 Add 'null' string validation if null is returned on cigroups
  build.gradle
  tests/jenkins/jobs/RunIntegTestScript_Jenkinsfile
  tests/jenkins/jobs/RunIntegTestScript_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_LocalPath_Jenkinsfile
  tests/jenkins/jobs/RunIntegTestScript_LocalPath_Jenkinsfile.txt
  tests/jenkins/jobs/RunIntegTestScript_LocalPath_Switch_Non_Root_Jenkinsfile
  tests/jenkins/jobs/RunIntegTestScript_LocalPath_Switch_Non_Root_Jenkinsfile.txt
  vars/runIntegTestScript.groovy
Labels: backport 8.x

#628 Update aptly version check to support ubuntu2404
  tests/jenkins/jobs/PromoteRepos_Jenkinsfile.txt
  vars/promoteRepos.groovy
Labels: backport 8.3
